### ISSUE TITLE
mate-screensaver-command harcodeado

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-tda#10]
El programa intenta ejecutar mate-screensaver-command. Deberia comprobar (en todo caso) si el ejecutable existe.
Tambien tener en cuenta que usando sobre gnome el screensaver es diferente (inclusive para uso en otros desktops o usando xscreensaver simplemente).

**Comment by iglosiggio** [comment]
http://linux.die.net/man/1/xdg-screensaver Creo que es la solución más decente posible para reemplazarlo, dependemos de que cada DE implemente lo necesario de freedesktop.org

**Comment by iglosiggio** [comment]
Ahí debería andar, testealo @ftoledo 

No pude hacerlo buildear porque parece que [en la vm de strider no hay internet](http://ci.huayragnulinux.com.ar/huayralinux/huayra-tda/job/57e2c2f15c172f2c7a3af1d6)
